name: Deploy Flask App to EC2

on: pull_request

env:
  HOSTING_DIR: /home/ec2-user/tripplanner-backend/itinerary

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify that the job runs on a self-hosted runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5 # Github does not support setup-python on anything other than #Ubuntu
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Clean hosting folder
      run: |
        rm -rf $HOSTING_DIR/host
        mkdir $HOSTING_DIR/host

    - name: Move files to hosting folder
      run: cp -r ./* $HOSTING_DIR/host

    - name: Create virtual env and install requirements in hosting folder
      run: |
        cd $HOSTING_DIR/host
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install gunicorn

    - name: Copy settings file to host
      run: cp $HOSTING_DIR/settings.py $HOSTING_DIR/host/
    
    - name: Reload/start WSGI service
      run: |
        sudo systemctl daemon-reload
        sudo systemctl start tripplanner-itinerary
        sudo systemctl enable tripplanner-itinerary
        sudo systemctl status tripplanner-itinerary